package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"url-shortener/internal/graph"
	"url-shortener/internal/graph/gqmodel"
)

// ShortenURL is the resolver for the shortenURL field.
func (r *mutationResolver) ShortenURL(ctx context.Context, input *gqmodel.ShortenURL) (*gqmodel.URL, error) {
	panic(fmt.Errorf("not implemented: ShortenURL - shortenURL"))
}

// Urls is the resolver for the urls field.
func (r *queryResolver) Urls(ctx context.Context) ([]*gqmodel.URL, error) {
	panic(fmt.Errorf("not implemented: Urls - urls"))
}

// URL is the resolver for the url field.
func (r *queryResolver) URL(ctx context.Context, id int) (*gqmodel.URL, error) {
	panic(fmt.Errorf("not implemented: URL - url"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
