package gq_resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"url-shortener/internal/graph"
	"url-shortener/internal/graph/gqmodel"
)

// CreateDomain is the resolver for the createDomain field.
func (r *mutationResolver) CreateDomain(ctx context.Context, input gqmodel.CreateDomain) (*gqmodel.Domain, error) {
	return r.DomainService.Create(input)
}

// UpdateDomain is the resolver for the updateDomain field.
func (r *mutationResolver) UpdateDomain(ctx context.Context, id int, input gqmodel.CreateDomain) (*gqmodel.Domain, error) {
	return r.DomainService.Update(id, input)
}

// DeleteDomain is the resolver for the deleteDomain field.
func (r *mutationResolver) DeleteDomain(ctx context.Context, id int) (string, error) {
	return r.DomainService.Delete(id)
}

// CreateLink is the resolver for the createLink field.
func (r *mutationResolver) CreateLink(ctx context.Context, input gqmodel.CreateLink) (*gqmodel.Link, error) {
	return r.LinkService.Create(input)
}

// UpdateLink is the resolver for the updateLink field.
func (r *mutationResolver) UpdateLink(ctx context.Context, id int, input gqmodel.CreateLink) (*gqmodel.Link, error) {
	return r.LinkService.Update(id, input)
}

// DeleteLink is the resolver for the deleteLink field.
func (r *mutationResolver) DeleteLink(ctx context.Context, id int) (string, error) {
	return r.LinkService.Delete(id)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input gqmodel.CreateUser) (*gqmodel.User, error) {
	return r.UserService.Create(input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int, input gqmodel.CreateUser) (*gqmodel.User, error) {
	return r.UserService.Update(id, input)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id int) (string, error) {
	return r.UserService.Delete(id)
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
