package gq_resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"url-shortener/internal/graph"
	"url-shortener/internal/graph/gqmodel"
)

// CreateDomain is the resolver for the createDomain field.
func (r *mutationResolver) CreateDomain(ctx context.Context, input *gqmodel.CreateDomain) (*gqmodel.Domain, error) {
	panic(fmt.Errorf("not implemented: CreateDomain - createDomain"))
}

// UpdateDomain is the resolver for the updateDomain field.
func (r *mutationResolver) UpdateDomain(ctx context.Context, input *gqmodel.CreateDomain) (*gqmodel.Domain, error) {
	panic(fmt.Errorf("not implemented: UpdateDomain - updateDomain"))
}

// DeleteDomain is the resolver for the deleteDomain field.
func (r *mutationResolver) DeleteDomain(ctx context.Context, id *int) (string, error) {
	panic(fmt.Errorf("not implemented: DeleteDomain - deleteDomain"))
}

// CreateLink is the resolver for the createLink field.
func (r *mutationResolver) CreateLink(ctx context.Context, input gqmodel.CreateLink) (*gqmodel.Link, error) {
	panic(fmt.Errorf("not implemented: CreateLink - createLink"))
}

// UpdateLink is the resolver for the updateLink field.
func (r *mutationResolver) UpdateLink(ctx context.Context, input gqmodel.CreateLink) (*gqmodel.Link, error) {
	panic(fmt.Errorf("not implemented: UpdateLink - updateLink"))
}

// DeleteLink is the resolver for the deleteLink field.
func (r *mutationResolver) DeleteLink(ctx context.Context, id *int) (string, error) {
	panic(fmt.Errorf("not implemented: DeleteLink - deleteLink"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input *gqmodel.CreateUser) (*gqmodel.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input *gqmodel.CreateUser) (*gqmodel.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id *int) (string, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
