package gq_resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"url-shortener/internal/graph"
	"url-shortener/internal/graph/gqmodel"
)

// Links is the resolver for the Links field.
func (r *queryResolver) Links(ctx context.Context, pagination gqmodel.PaginationQuery) (*gqmodel.LinksResult, error) {
	panic(fmt.Errorf("not implemented: Links - Links"))
}

// GetLink is the resolver for the getLink field.
func (r *queryResolver) GetLink(ctx context.Context, id int) (*gqmodel.Link, error) {
	panic(fmt.Errorf("not implemented: GetLink - getLink"))
}

// Domains is the resolver for the domains field.
func (r *queryResolver) Domains(ctx context.Context, pagination gqmodel.PaginationQuery, sort *gqmodel.SortBy) (*gqmodel.DomainsResult, error) {
	panic(fmt.Errorf("not implemented: Domains - domains"))
}

// GetDomain is the resolver for the getDomain field.
func (r *queryResolver) GetDomain(ctx context.Context, id *int) (*gqmodel.Domain, error) {
	panic(fmt.Errorf("not implemented: GetDomain - getDomain"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, pagination gqmodel.PaginationQuery, sort *gqmodel.SortBy) (*gqmodel.UserResult, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id *int) (*gqmodel.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
