package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"url-shortener/internal/graph/gqmodel"
)

// ShortenURL is the resolver for the shortenURL field.
func (r *mutationResolver) ShortenURL(ctx context.Context, input *gqmodel.ShortenURL) (*gqmodel.URL, error) {
	return r.URLService.Create(*input)
}

// Urls is the resolver for the urls field.
func (r *queryResolver) Urls(ctx context.Context) ([]*gqmodel.URL, error) {
	fields := r.GetRequestedFields(ctx)
	return r.URLService.Repo.Get(fields)
}

// URL is the resolver for the url field.
func (r *queryResolver) URL(ctx context.Context, id int) (*gqmodel.URL, error) {
	return r.URLService.Repo.Find(id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
