// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqmodel

type Mutation struct {
}

type Query struct {
}

type URL struct {
	ID          string `json:"id"`
	OriginalURL string `json:"originalURL"`
	ShortURL    string `json:"shortURL"`
	CreatedAt   string `json:"createdAt"`
}
