// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqmodel

type Mutation struct {
}

type Query struct {
}

type ShortenURL struct {
	OriginalURL string  `json:"original_url"`
	Hash        *string `json:"hash,omitempty"`
	DomainID    *int    `json:"domain_id,omitempty"`
}

type URL struct {
	ID          int    `json:"id"`
	OriginalURL string `json:"original_url"`
	Hash        string `json:"hash"`
	DomainID    *int   `json:"domain_id,omitempty"`
	IsActive    bool   `json:"is_active"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}
